################## BOOK #####################

### Read book
GET http://localhost:8000/books

### Create book
POST http://localhost:8000/books
Content-Type: application/json

{
  "title": "Deux gouttes d'eau",
  "resume": "Une jeune femme est retrouvée morte dans son appartement de Boulogne-Billancourt, massacrée à coups de hache. Elle s'appelle Élodie et son ami, Antoine Deloye, est identifié sur l'enregistrement d'une caméra de vidéosurveillance de la ville, sortant de chez elle, l'arme du crime à la main. Immédiatement placé en garde à vue, Antoine s'obstine à nier malgré les évidences. Il accuse son frère jumeau, Franck, d'avoir profité de leur ressemblance pour mettre au point une machination destinée à le perdre. Quand Franck Deloye arrive au commissariat central pour être entendu, le trouble est immense : il est impossible de différencier les deux hommes, qui se ressemblent, littéralement, comme deux gouttes d'eau... ",
  "cover": "https://images-na.ssl-images-amazon.com/images/I/51DyTj1f28L._SX210_.jpg",
  "genre": "Policier"
}

### Update book
PUT http://localhost:8000/books/1
Content-Type: application/json

{
  "genre": "Thriller"
}

### Delete book
DELETE http://localhost:8000/books/2

################## REVIEW #####################

### Read reviews
GET http://localhost:8000/reviews

### Read reviews by id
GET http://localhost:8000/reviews/1

### Create review
POST http://localhost:8000/reviews
Content-Type: application/json

{
  "review": "Très bon livre policier",
  "book_id": "1"
}